apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "habit-tracker.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "habit-tracker.labels" . | nindent 4 }}
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.port | int }}
          envFrom:
            - configMapRef:
                name: {{ include "habit-tracker.fullname" . }}-config
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "habit-tracker.secretName" . }}
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "habit-tracker.secretName" . }}
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@{{ include "habit-tracker.mongodbServiceName" . }}:27017/$(MONGO_DB_NAME)?authSource=admin"
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.config.port | int }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.config.port | int }}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}