apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "habit-tracker.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "habit-tracker.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  MONGO_DB_NAME: {{ .Values.config.mongoDbName | quote }}