apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "habit-tracker.fullname" . }}-mongodb-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "habit-tracker.labels" . | nindent 4 }}
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}